### PR TITLE
Change event

### LINKED ISSUE #23: The component fires too many value-changed events
The following should pass:
```
it('should fire only one value-change event', () => {
  const spy = sinon.spy();
  timePicker.addEventListener('value-changed', spy);
  timePicker.value = "12:00";
  expect(spy.callCount).to.equal(1);
  timePicker.value = "";
  expect(spy.callCount).to.equal(2);
});
```

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fix #23

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-time-picker.html, line 212 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-LCmY8IF2GCwa0y7Hvin:-LCmY8IF2GCwa0y7Hvio:b5qmkqh) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/de7337160e235df3227dfa69af47890a00e777f2/src/vaadin-time-picker.html#L212)):*
> ```HTML
> 
>         __valueChanged(value, oldValue) {
>           const parsedObj = this.__parseISO(value) || '';
> ```

`parseObj` is a js object or null,  it's very confusing to set it to an empty value.

---

*[src/vaadin-time-picker.html, line 215 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-LCmYa2I0qEmmvcDl2tX:-LCmYa2J65oylzurPp17:b-a2yszl) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/de7337160e235df3227dfa69af47890a00e777f2/src/vaadin-time-picker.html#L215)):*
> ```HTML
> 
>           const valueFromCurrent = this.__formatISO(parsedObj) || '';
>           const valueFromOld = this.__formatISO(this.__parseISO(oldValue)) || '';
> ```

makes not sense to format the oldValue, it should be an already valid formatted string

---

*[src/vaadin-time-picker.html, line 227 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-LCmZHyPCdG_J6GOs7nn:-LCmZHyPCdG_J6GOs7no:b8ax2l1) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/de7337160e235df3227dfa69af47890a00e777f2/src/vaadin-time-picker.html#L227)):*
> ```HTML
> 
>         __onInputChange(e) {
>           const parsedObj = this.i18n.parseTime(this.__dropdownElement.value) || '';
> ```

same comments than above

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 212 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-LCmY8IF2GCwa0y7Hvin:-LCmdirM82igsOnlf6U-:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/de7337160e235df3227dfa69af47890a00e777f2/src/vaadin-time-picker.html#L212)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

`parseObj` is a js object or null,  it's very confusing to set it to an empty value.
</blockquote></details>

Updated.

---

*[src/vaadin-time-picker.html, line 215 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-LCmYa2I0qEmmvcDl2tX:-LCmdmT4D0HrD-wITt-v:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/de7337160e235df3227dfa69af47890a00e777f2/src/vaadin-time-picker.html#L215)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

makes not sense to format the oldValue, it should be an already valid formatted string
</blockquote></details>

Updated.

---

*[src/vaadin-time-picker.html, line 227 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-LCmZHyPCdG_J6GOs7nn:-LCmdneHBdXmVdMYC-sb:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/de7337160e235df3227dfa69af47890a00e777f2/src/vaadin-time-picker.html#L227)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

same comments than above
</blockquote></details>

Updated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25)*

**Comment by tomivirkki** [comment]
*[test/custom-functions.html, line 35 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-LCmeF5nDIOyzmkUzURc:-LCmeF5nDIOyzmkUzURd:ble38qj) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/2adda51a0d237c913d7129864ff5a49976057e36/test/custom-functions.html#L35)):*
> ```HTML
> 
>       it('should use custom formatter if that exists', function() {
>         timePicker.set('i18n.formatTime', sinon.stub().withArgs({hours: 12, minutes: 0}).returns('12:00 AM'));
> ```

Why is this test invalidated?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/custom-functions.html, line 35 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-LCmeF5nDIOyzmkUzURc:-LCmuuzs2mmMpVtQNQj_:b-bvwhm5) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/2adda51a0d237c913d7129864ff5a49976057e36/test/custom-functions.html#L35)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is this test invalidated?
</blockquote></details>

Restored.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 212 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-LCmY8IF2GCwa0y7Hvin:-LCn8wlH1xjWDUfTy8q_:bdf7vwo) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/de7337160e235df3227dfa69af47890a00e777f2/src/vaadin-time-picker.html#L212)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

It is redundant to set it to `|| null`  method returns  `undefined` which is ok for the object. 

Below you just check for the object existence,  no need for `&& parsedObject === null`  just  `&& parsedObject` 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 212 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-LCmY8IF2GCwa0y7Hvin:-LCnMgDh-eZGxusYyowj:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/de7337160e235df3227dfa69af47890a00e777f2/src/vaadin-time-picker.html#L212)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It is redundant to set it to `|| null`  method returns  `undefined` which is ok for the object. 

Below you just check for the object existence,  no need for `&& parsedObject === null`  just  `&& parsedObject` 


</blockquote></details>

Updated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-:-LCoRzxM--AA35R3yKqE:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25#-:-LD0yNzM9bL5qjaJ8dq9:bnfp4nl)*

**Pull request merged**
