### PR TITLE
Align props and mixin with other elements. Implement readonly/disabled.

### LINKED ISSUE #10: Disabled and readonly states
child of #1

### PR DESCRIPTION
**Pull request by manolo**
Fixes #10

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/27)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/27#-:-LD0jbR59PMSFpBAvL4S:bnfp4nl)*

**Comment by manolo** [comment]
This includes #24 now

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/27#-:-LD1wqOB8hBE-N6wh70w:b-7jygjh)*

**Comment by YuriyVaadin** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/27)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/27#-:-LDB-ScS88XHcHb0dWrd:bnfp4nl)*

**Pull request merged**
