### PR TITLE
Add dropdown

### LINKED ISSUE #5: Add dropdown
child of #1

- wrap the textfield in a vaadin-combo-box-light
 - use `filteredItems` (No filtering)
 - `allowCustomValue`
- Only exactly matching option is highlighted
- Hour resolution
- Clock icon toggle
- Tests

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #5

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[.travis.yml, line 36 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBukFZ1B8o-qBTkfV9C:-LBukFZ1B8o-qBTkfV9D:b-1b7ouq) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/.travis.yml#L36)):*
> ```YAML
> 
>   - if [[ "$POLYMER" = "3" ]]; then
>       npm install -g yarn magi-cli polymer-cli@next &&
> ```

BTW please change Travis config to install `polymer-cli@next` for both P2 and P3, see e. g. vaadin/vaadin-dropdown-menu@8be35c9

---

*[src/vaadin-time-picker.html, line 10 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBvd6vSChLYQYfPVG4d:-LBvd6vSChLYQYfPVG4e:b51uc9r) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/src/vaadin-time-picker.html#L10)):*
> ```HTML
> <link rel="import" href="../../vaadin-themable-mixin/vaadin-themable-mixin.html">
> <link rel="import" href="../../vaadin-element-mixin/vaadin-element-mixin.html">
> <link rel="import" href="../../vaadin-combo-box/vaadin-combo-box-light.html">
> ```

please use the "src" version

---

*[src/vaadin-time-picker.html, line 25 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBvdEtwCQKyPgUtTObN:-LBvdEtwCQKyPgUtTObO:b-uturo6) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/src/vaadin-time-picker.html#L25)):*
> ```HTML
>       }
> 
>       .toggle-button {
> ```

BTW should we maybe expose it as a shadow part? Not a blocker though

---

*[src/vaadin-time-picker.html, line 34 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBukeW782JTAU2pGP6U:-LBukeW782JTAU2pGP6V:b-qoghcm) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/src/vaadin-time-picker.html#L34)):*
> ```HTML
>       </template>
>       <vaadin-time-picker-text-field class="input">
>         <iron-icon slot="suffix" role="button" icon="vaadin:clock" class="toggle-button"></iron-icon>
> ```

why don't we use "clock" icon from Lumo instead? 
Pulling in the whole bundle of `

---

*[test/dropdown-test.html, line 25 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBul0Kk8HiBm2kNdPzi:-LBul0Kk8HiBm2kNdPzj:b735qh6) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/test/dropdown-test.html#L25)):*
> ```HTML
>       beforeEach(function() {
>         timePicker = fixture('default');
>         comboBoxLight = timePicker.shadowRoot.querySelector('vaadin-combo-box-light');
> ```

you can just use reference to `timePicker._dropdownElement` instead

---

*[test/dropdown-test.html, line 29 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBumGwDAhx-esQ3ZLWv:-LBumGwDAhx-esQ3ZLWw:b85fv79) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/test/dropdown-test.html#L29)):*
> ```HTML
> 
>       it('vaadin-combo-box-light should exist', function() {
>         expect(comboBoxLight.localName).to.be.equal('vaadin-combo-box-light');
> ```

the test passes even if we remove the import of the `vaadin-combo-box-light.html` so I would suggest to enhance it by adding the following check:

```js
expect(comboBoxLight instanceof Vaadin.ComboBoxLightElement).to.be.true;
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/vaadin-time-picker.html, line 34 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBukeW782JTAU2pGP6U:-LBvdRRb0i47hNFFnBEl:bbopf5l) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/src/vaadin-time-picker.html#L34)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

why don't we use "clock" icon from Lumo instead? 
Pulling in the whole bundle of `
</blockquote></details>

... the whole bundle of "vaadin-icons" for just 1 icon does not seem good, as we will rewrite it anyways.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15)*

**Comment by YuriyVaadin** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[.travis.yml, line 36 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBukFZ1B8o-qBTkfV9C:-LBzOS448y3BSYmG55X6:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/.travis.yml#L36)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW please change Travis config to install `polymer-cli@next` for both P2 and P3, see e. g. vaadin/vaadin-dropdown-menu@8be35c9
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 10 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBvd6vSChLYQYfPVG4d:-LBzORXSCmk2VKrPvmv2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/src/vaadin-time-picker.html#L10)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

please use the "src" version
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 25 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBvdEtwCQKyPgUtTObN:-LBzORIS4PN9Ozx7GZE_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/src/vaadin-time-picker.html#L25)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW should we maybe expose it as a shadow part? Not a blocker though
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 34 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBukeW782JTAU2pGP6U:-LBzOQh-AadH6yGYgAST:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/src/vaadin-time-picker.html#L34)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

... the whole bundle of "vaadin-icons" for just 1 icon does not seem good, as we will rewrite it anyways.
</blockquote></details>

Done.

---

*[test/dropdown-test.html, line 25 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBul0Kk8HiBm2kNdPzi:-LBzOQ0_CailpF4tDZIG:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/test/dropdown-test.html#L25)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

you can just use reference to `timePicker._dropdownElement` instead
</blockquote></details>

Done.

---

*[test/dropdown-test.html, line 29 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBumGwDAhx-esQ3ZLWv:-LBzOPgK1vnkw3OGT1Oo:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c148caeca49778aa42ab10c31fb566b1df089a7e/test/dropdown-test.html#L29)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

the test passes even if we remove the import of the `vaadin-combo-box-light.html` so I would suggest to enhance it by adding the following check:

```js
expect(comboBoxLight instanceof Vaadin.ComboBoxLightElement).to.be.true;
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15)*

**Comment by tomivirkki** [comment]
*[src/vaadin-time-picker.html, line 89 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBzW3S-9bEmPWtVZ4_V:-LBzW3S-9bEmPWtVZ4_W:b1w5ftv) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/574a3663a46010da0a090663e7f9e2b98fd1d129/src/vaadin-time-picker.html#L89)):*
> ```HTML
>             },
> 
>             dropdownItems: {
> ```

I assume this isn't supposed to be public

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15)*

**Comment by tomivirkki** [comment]
*[src/vaadin-time-picker.html, line 106 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBzWFCq9UdtY7WXCnqs:-LBzWFCq9UdtY7WXCnqt:bpweufx) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/574a3663a46010da0a090663e7f9e2b98fd1d129/src/vaadin-time-picker.html#L106)):*
> ```HTML
>         }
> 
>         _generateDropdownList() {
> ```

Let's follow Polymer's conventions on private/protected members https://www.polymer-project.org/2.0/docs/devguide/properties#private-and-protected-properties

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15)*

**Comment by YuriyVaadin** [comment]
Review status: 3 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 89 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBzW3S-9bEmPWtVZ4_V:-LBzYzozA6gMHldcSW0V:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/574a3663a46010da0a090663e7f9e2b98fd1d129/src/vaadin-time-picker.html#L89)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I assume this isn't supposed to be public
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 106 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBzWFCq9UdtY7WXCnqs:-LBzZ-1DDxiCk1COt_9C:b2wz5zd) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/574a3663a46010da0a090663e7f9e2b98fd1d129/src/vaadin-time-picker.html#L106)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Let's follow Polymer's conventions on private/protected members https://www.polymer-project.org/2.0/docs/devguide/properties#private-and-protected-properties
</blockquote></details>

Will be handled in https://github.com/vaadin/vaadin-time-picker/issues/8

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15)*

**Comment by tomivirkki** [comment]
*[src/vaadin-time-picker.html, line 31 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBzc4Xp9FJD0agMsKCi:-LBzc4Xp9FJD0agMsKCj:bnjjfpu) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/df96a1883eb17d5b4e6aee4da0096d482d8fb322/src/vaadin-time-picker.html#L31)):*
> ```HTML
>     <vaadin-combo-box-light allow-custom-value item-label-path="value" value="{{value}}" filtered-items="[[_dropdownItems]]">
>       <template>
>         [[item.label]]
> ```

Slight misunderstanding here about what should be rendered in the list items. The items were supposed to show the same label as the input but on hour's intervals. Sorry for the bad description in the ticket. But it's changed in the following PR so it's not a blocker here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15)*

**Comment by tomivirkki** [comment]
*[src/vaadin-time-picker.html, line 189 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-LBze-IV43963FFxRgiU:-LBze-IV43963FFxRgiV:b-4mddsv) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/df96a1883eb17d5b4e6aee4da0096d482d8fb322/src/vaadin-time-picker.html#L189)):*
> ```HTML
>           this._dropdownItems = this._generateDropdownList();
>           // Need to update selected item after regenerating of the list
>           this._dropdownElement.selectedItem = this._dropdownItems.filter(item => item.value === this.value)[0];
> ```

This update is only needed because the value is set before new items are generated to the dropdown. Change the order and this step can be skipped.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-:-LBzePLPBg5dbaGtKcXB:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-:-LBzp5cz7WJk4-5AmtfO:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15#-:-LBzpdiG4dUkrmzgWcnV:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15)*

**Pull request merged**
