### PR TITLE
Fixes to UX findings

### LINKED ISSUE #32: Add label and placeholder to demos
Add time format to the labels of the demo time picker "Start time (hh:mm)"

### PR DESCRIPTION
**Pull request by manolo**
Fixes #32 #37 #44 #45

Connects to #32
Connects to #37 
Connects to #44
Connects to #45

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[demo/time-picker-basic-demos.html, line 24 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54#-LEh_VBB1Qq7uLVL0ZW8:-LEh_VBB1Qq7uLVL0ZW9:bd67zvv) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/967101a089fb847d5bfb48ef5af5dbd9109a499c/demo/time-picker-basic-demos.html#L24)):*
> ```HTML
>     <vaadin-demo-snippet id="time-picker-basic-demos-step-example">
>       <template preserve-content>
>         <vaadin-time-picker step="0.5" label="Video duration" placeholder="hh:mm:ss.fff"></vaadin-time-picker>
> ```

As noticed in the UX sessions, the placeholder doesn't really help the users since it disappears right after you start typing. Would the patterns fit in the labels?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @manolo)

---

*[demo/time-picker-basic-demos.html, line 24 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54#-LEh_VBB1Qq7uLVL0ZW8:-LEhcsRv1-1ZC6qg3cBg:bosjtj4) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/967101a089fb847d5bfb48ef5af5dbd9109a499c/demo/time-picker-basic-demos.html#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

As noticed in the UX sessions, the placeholder doesn't really help the users since it disappears right after you start typing. Would the patterns fit in the labels?
</blockquote></details>

Maybe we can add format to label in demos requiring the user to use the keyboard, the one with millisec resolution.
Others have the dropdown enabled.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54)*

**Comment by tomivirkki** [comment]
*[demo/time-picker-basic-demos.html, line 24 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54#-LEh_VBB1Qq7uLVL0ZW8:-LEhlwLk9IeqWtVDPigZ:b-n5m1am) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/967101a089fb847d5bfb48ef5af5dbd9109a499c/demo/time-picker-basic-demos.html#L24)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Maybe we can add format to label in demos requiring the user to use the keyboard, the one with millisec resolution.
Others have the dropdown enabled.
</blockquote></details>

The current appearance of the dropdown isn't permanent so let's not rely on it including hints about the pattern.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @manolo)

---

*[demo/time-picker-basic-demos.html, line 24 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54#-LEh_VBB1Qq7uLVL0ZW8:-LEhsIcDCahSg_AqYyDX:b-vxen1h) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/967101a089fb847d5bfb48ef5af5dbd9109a499c/demo/time-picker-basic-demos.html#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The current appearance of the dropdown isn't permanent so let's not rely on it including hints about the pattern.
</blockquote></details>

Moved format to label, so as developer sees a way for showing format  when user is typing.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54)*

**Comment by tomivirkki** [comment]
*[demo/time-picker-basic-demos.html, line 24 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54#-LEh_VBB1Qq7uLVL0ZW8:-LEiAqul1qSDaTPL-SaD:bvyytf5) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/967101a089fb847d5bfb48ef5af5dbd9109a499c/demo/time-picker-basic-demos.html#L24)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Moved format to label, so as developer sees a way for showing format  when user is typing.
</blockquote></details>

Advanced demo still has placeholder

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54)*

**Comment by tomivirkki** [comment]
*[demo/time-picker-basic-demos.html, line 39 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54#-LEiB1Oh4-uLl7YGLQpC:-LEiB1Oh4-uLl7YGLQpD:b-m1phcn) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/299cbbd1ae9f0188ab7687f5ef7635f042bb8d7d/demo/time-picker-basic-demos.html#L39)):*
> ```HTML
>               formatTime: function(timeObject) {
>                 if (timeObject) {
>                   const pad = function(n = 0) {
> ```

Default parameters is a ES6 feature so this doesn't work in IE11

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @manolo)

---

*[demo/time-picker-basic-demos.html, line 24 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54#-LEh_VBB1Qq7uLVL0ZW8:-LEiEDDO9PbS8cffH3IS:b-2xnr27) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/967101a089fb847d5bfb48ef5af5dbd9109a499c/demo/time-picker-basic-demos.html#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Advanced demo still has placeholder
</blockquote></details>

was intentional, removed anyways

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @tomivirkki)

---

*[demo/time-picker-basic-demos.html, line 39 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54#-LEiB1Oh4-uLl7YGLQpC:-LEiELnx8vAamvD24xT1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/299cbbd1ae9f0188ab7687f5ef7635f042bb8d7d/demo/time-picker-basic-demos.html#L39)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Default parameters is a ES6 feature so this doesn't work in IE11
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54#-:-LEiH5VlBaGPG5u-IWwe:bnfp4nl)*

**Pull request merged**
