### PR TITLE
align properties with other elements

### PR DESCRIPTION
**Pull request by manolo**
This PR is to facilitate working simultaneously in #10 and #11
Tests and demos for features added will come in separated PR.

Connected to #10 
Connected to #11

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
Other than not blocking nit, :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-time-picker.html, line 39 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LCm_zQr9NiZCVE-iMmR:-LCm_zQr9NiZCVE-iMmS:b-pcmfiz) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/4d519b5e6f82231198eca3bf49f11fb16414992a/src/vaadin-time-picker.html#L39)):*
> ```HTML
>           disabled="[[disabled]]"
>           prevent-invalid-input="[[preventInvalidInput]]"
>           pattern="[[pattern]]"
> ```

Do we really need to expose `pattern` and `preventInvalidInput`? 
It makes sense in terms of exposing all of the properties/attributes, but could affect the setting of the input value / value functionality.
Not a blocker.

---

*[src/vaadin-time-picker.html, line 284 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LCmahzv3gXCQ0Ms9IAK:-LCmahzv3gXCQ0Ms9IAL:b-9p50wx) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/4d519b5e6f82231198eca3bf49f11fb16414992a/src/vaadin-time-picker.html#L284)):*
> ```HTML
>         __valueChanged(value, oldValue) {
>           const parsedObj = this.__parseISO(value);
>           if (parsedObj) {
> ```

There is no need to change it here as it's not related to the task and #25 will change the logic anyway.
Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-:-LCmb-Ge3gTWeE9DafOh:b-sl31wl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-time-picker.html, line 39 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LCm_zQr9NiZCVE-iMmR:-LCn3P_XAY9Cc7qmX_MZ:bkaqgyo) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/4d519b5e6f82231198eca3bf49f11fb16414992a/src/vaadin-time-picker.html#L39)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Do we really need to expose `pattern` and `preventInvalidInput`? 
It makes sense in terms of exposing all of the properties/attributes, but could affect the setting of the input value / value functionality.
Not a blocker.
</blockquote></details>

They are exposed in other elements, but they are useful, since our validation relies on the native-input.checkValidity() which considers these cases. We might for instance define a range of valid hours by setting a pattern regexp. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24)*

**Comment by tomivirkki** [comment]
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-time-picker.html, line 36 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pKC01iXlqVn17O0P:-LD0pKC01iXlqVn17O0Q:b-8jf6re) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L36)):*
> ```HTML
>           autocomplete="off"
>           label="[[label]]"
>           required="[[required]]"
> ```

How can you have required if you can't validate the field?

---

*[src/vaadin-time-picker.html, line 39 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pWI--rRIHBbhcEv_:-LD0pWI--rRIHBbhcEva:b8xq46a) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L39)):*
> ```HTML
>           disabled="[[disabled]]"
>           prevent-invalid-input="[[preventInvalidInput]]"
>           pattern="[[pattern]]"
> ```

Why would you this in timepicker?

---

*[src/vaadin-time-picker.html, line 43 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pdHQDcnBvB_jTEjv:-LD0pdHQDcnBvB_jTEjw:b-yxezpk) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L43)):*
> ```HTML
>           autofocus="[[autofocus]]"
>           placeholder="[[placeholder]]"
>           readonly="[[readonly]]">
> ```

Doesn't work! The overlay can be opened by clicking and a value can be selected

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24)*

**Comment by manolo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 36 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pKC01iXlqVn17O0P:-LD0tcYx599CuVpwNskr:b8d1976) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L36)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

How can you have required if you can't validate the field?
</blockquote></details>

This PR is finished with #26 and #27  that are based on this

---

*[src/vaadin-time-picker.html, line 39 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pWI--rRIHBbhcEv_:-LD0sxfkAC13GI7K7ZuW:bmdpn4a) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L39)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why would you this in timepicker?
</blockquote></details>

We need this in order to use native validation in input. There is  a test in PR #26 which complements this.

---

*[src/vaadin-time-picker.html, line 43 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pdHQDcnBvB_jTEjv:-LD0tTmgBXYdfgJ7z8sJ:b9zx4gi) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L43)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Doesn't work! The overlay can be opened by clicking and a value can be selected
</blockquote></details>

This is implemented in PR #27 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24)*

**Comment by tomivirkki** [comment]
*[src/vaadin-time-picker.html, line 43 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pdHQDcnBvB_jTEjv:-LD0vA8Y7lgi7EnTtLlu:b-o9sf9y) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L43)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This is implemented in PR #27 
</blockquote></details>

So we should merge a broken PR to master because it's meant to be fixed later?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24)*

**Comment by manolo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 43 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pdHQDcnBvB_jTEjv:-LD0xaHQ5PvKcJ0m-91s:b-85cmuw) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L43)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

So we should merge a broken PR to master because it's meant to be fixed later?
</blockquote></details>

Not a big problem, since we already have a ticket for implementing it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24)*

**Comment by tomivirkki** [comment]
*[src/vaadin-time-picker.html, line 39 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pWI--rRIHBbhcEv_:-LD0xkqR4xFU58cJAYAa:b-if0kh7) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L39)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

We need this in order to use native validation in input. There is  a test in PR #26 which complements this.
</blockquote></details>

Date-picker doesn't have pattern or preventInvalidInput. Shouldn't these components be aligned?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24)*

**Comment by manolo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/vaadin-time-picker.html, line 39 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pWI--rRIHBbhcEv_:-LD0zpub2hwix38kwaFN:b3oza74) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L39)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Date-picker doesn't have pattern or preventInvalidInput. Shouldn't these components be aligned?
</blockquote></details>

I think date-picker should implement it. Otherwise developer cannot prevent user writing `foo` in the field instead of valid dates

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24)*

**Comment by tomivirkki** [comment]
*[src/vaadin-time-picker.html, line 39 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pWI--rRIHBbhcEv_:-LD14B6vDB4Vzo-JlKir:bklxfmd) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L39)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think date-picker should implement it. Otherwise developer cannot prevent user writing `foo` in the field instead of valid dates
</blockquote></details>

Then you can create a suggestion ticket for that feature that we can discuss separately.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24)*

**Comment by manolo** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 39 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pWI--rRIHBbhcEv_:-LD1HpeZ3rQXFUtX2BKi:b5pmrkx) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L39)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Then you can create a suggestion ticket for that feature that we can discuss separately.
</blockquote></details>

Reported https://github.com/vaadin/vaadin-date-picker/issues/554

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24)*

**Comment by YuriyVaadin** [comment]
:lgtm_cancel: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 43 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pdHQDcnBvB_jTEjv:-LD1VHXF158-111juoFF:b7kin6g) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L43)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Not a big problem, since we already have a ticket for implementing it.
</blockquote></details>

This test is not passing in this PR or in #27:
```
it('dropdown should not be shown when read-only', (done) => {
  timePicker.readonly = true;
  timePicker.__inputElement.dispatchEvent(new CustomEvent('click', {bubbles: true}));
  expect(timePicker.__dropdownElement.opened).to.be.false;
});
```
Probably it's my mistake, that I haven't checked this functionality previously, but as we are implementing `readonly` in this PR, I guess it should be fixed here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-:-LD1Vjgz8_SH5WuXoYmU:b8b79qu)*

**Comment by YuriyVaadin** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 43 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24#-LD0pdHQDcnBvB_jTEjv:-LD1s6zD-hs78RDa209L:b-oecivm) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/02b995bb77f56284302aed0718afe975fee5e306/src/vaadin-time-picker.html#L43)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

This test is not passing in this PR or in #27:
```
it('dropdown should not be shown when read-only', (done) => {
  timePicker.readonly = true;
  timePicker.__inputElement.dispatchEvent(new CustomEvent('click', {bubbles: true}));
  expect(timePicker.__dropdownElement.opened).to.be.false;
});
```
Probably it's my mistake, that I haven't checked this functionality previously, but as we are implementing `readonly` in this PR, I guess it should be fixed here.
</blockquote></details>

Sorry, was confused with PRs ordering. Actually passing in #27, but not passing in #26.
So probably `readonly` and `disabled` should be added in #27 and #26 rebased on top of that one.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/24)*

**Comment by manolo** [comment]
Closing to avoid confusion. This is included in #27 and #26 depends on #27

**Pull request closed without merging**
