### PR TITLE
Improve Documentation

### LINKED ISSUE #8: Documentation
child of #1

- webcomponents.org example
- Readme
- Screenshot
- analysis.json
- Drop all mentions of "Polymer"
- Make all private members actually private (double underscores) instead of protected: https://www.polymer-project.org/2.0/docs/devguide/properties#private-and-protected-properties

### PR DESCRIPTION
**Pull request by manolo**
Fixes #8

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-time-picker.html, line 209 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-LCDlD9O60o__8Ydhjxq:-LCDlD9O60o__8Ydhjxr:b-rtrcxs) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/e143ce5165b76de2d71b02666a5df2c578d2bf3d/src/vaadin-time-picker.html#L209)):*
> ```HTML
> 
> 
>         /** The internal text-field element */
> ```

Could this be private instead of protected?

---

*[src/vaadin-time-picker.html, line 214 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-LCDl-4T3aKii2CwNC4U:-LCDl-4T3aKii2CwNC4V:b-rtrcxs) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/e143ce5165b76de2d71b02666a5df2c578d2bf3d/src/vaadin-time-picker.html#L214)):*
> ```HTML
>         }
> 
>         /** The internal combo-box element */
> ```

Could this be private instead of protected?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20)*

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 209 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-LCDlD9O60o__8Ydhjxq:-LCDqfwQ8s0g0YHCr77c:b-j9cxcz) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/e143ce5165b76de2d71b02666a5df2c578d2bf3d/src/vaadin-time-picker.html#L209)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Could this be private instead of protected?
</blockquote></details>

Not a special preference, but they are used in tests. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 209 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-LCDlD9O60o__8Ydhjxq:-LCE3BqY77W09WdFAb5q:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/e143ce5165b76de2d71b02666a5df2c578d2bf3d/src/vaadin-time-picker.html#L209)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Hmm...maybe we shouldn't expand our APIs just to support test cases
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 214 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-LCDl-4T3aKii2CwNC4U:-LCE3BI862eD4b3DuJOO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/e143ce5165b76de2d71b02666a5df2c578d2bf3d/src/vaadin-time-picker.html#L214)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Could this be private instead of protected?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20)*

**Comment by limonte** [comment]
Reviewed 5 of 8 files at r1, 2 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-time-picker.html, line 29 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-LCXwFsd-MXeHHrdmnmj:-LCXwFsd-MXeHHrdmnmk:b-g03f5d) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/82485ef2e0f16391c8d98a278eb92c9a4d9e1984/src/vaadin-time-picker.html#L29)):*
> ```HTML
>       }
>     </style>
>     <vaadin-combo-box-light allow-custom-value item-label-path="value" value="{{value}}" filtered-items="[[__dropdownItems]]">
> ```

What's the reason for double underscore?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20)*

**Comment by tomivirkki** [comment]
*[src/vaadin-time-picker.html, line 29 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-LCXwFsd-MXeHHrdmnmj:-LCXwSUt9shfBpEZhQs4:b5nb0w9) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/82485ef2e0f16391c8d98a278eb92c9a4d9e1984/src/vaadin-time-picker.html#L29)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

What's the reason for double underscore?
</blockquote></details>

See the ticket description

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-time-picker.html, line 29 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-LCXwFsd-MXeHHrdmnmj:-LCXzKpp7vvRL76wVeY2:b-3t5viy) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/82485ef2e0f16391c8d98a278eb92c9a4d9e1984/src/vaadin-time-picker.html#L29)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

See the ticket description
</blockquote></details>

Oh, I missed that Polymer (in|con)vention :) Thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-:-LCYHKaN-umn0nZDc69Z:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 79 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-LC_O6HV6bvN1-Ux-xQU:-LCbc4wCDPWMJGB53erW:by1ac52) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/d11ef90111c1c5fb75046b127f5c4036722b7043/src/vaadin-time-picker.html#L79)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

`__previousValue` is still used and shouldn't be removed
</blockquote></details>

It doesn't need to be declared as a property since it's an internal variable that it's not used in declarative elements, it's only used for memoized  values.
It's the same case than e.g. `__inputElement`  an internal property not used in declarative, and not declared in properties block

---

*[test/dropdown-test.html, line 25 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-LC_Ou0wEMANxYNDRIEB:-LCbcXnw5gxh_KzfUm0I:bejhly7) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/82485ef2e0f16391c8d98a278eb92c9a4d9e1984/test/dropdown-test.html#L25)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Why this change is required?
We can use `timePicker._dropdownElement` instead
</blockquote></details>

I removed read-only property `get _dropdownElement() ` in the component, it was only used for testing. 
Stuff only used in tests, should be declared in tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/20#-:-LCbgW8S-fGWfGIkex0W:bnfp4nl)*

**Pull request merged**
