### PR TITLE
Support iron-form

### PR DESCRIPTION
**Pull request by manolo**
Connected to #11

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-time-picker.html, line 410 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD0hcLk3aYTUGFwdJAj:-LD0hcLk3aYTUGFwdJAk:bvpfq16) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/0092a70c9c4c9223aaf361a89c51702b2f842224/src/vaadin-time-picker.html#L410)):*
> ```HTML
>         checkValidity() {
>           return this.__inputElement.focusElement.checkValidity() &&
>             (this.value === this.__inputElement.value || this.i18n.parseTime(this.__dropdownElement.value));
> ```

Why we are checking `this.value === this.__inputElement.value` At this point of time, I cannot come up with an idea when it can be true.

---

*[test/form-input.html, line 196 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD0jDpt-Kh2Sm4sjpuJ:-LD0jDpt-Kh2Sm4sjpuK:b-futwem) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/0092a70c9c4c9223aaf361a89c51702b2f842224/test/form-input.html#L196)):*
> ```HTML
>         expect(spy.called).to.be.false;
>       });
> ```

Should we add tests for submitting iron-form with `disabled`, `required` `time-picker` ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by manolo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 410 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD0hcLk3aYTUGFwdJAj:-LD0yzifDh-jwLjxZOjz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/0092a70c9c4c9223aaf361a89c51702b2f842224/src/vaadin-time-picker.html#L410)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Why we are checking `this.value === this.__inputElement.value` At this point of time, I cannot come up with an idea when it can be true.
</blockquote></details>

Done.

---

*[test/form-input.html, line 196 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD0jDpt-Kh2Sm4sjpuJ:-LD0uIL-9Z9IVA2Jbews:b33s89e) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/0092a70c9c4c9223aaf361a89c51702b2f842224/test/form-input.html#L196)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Should we add tests for submitting iron-form with `disabled`, `required` `time-picker` ?
</blockquote></details>

I'm covering the same cases than in date-picker, plus a couple of specific things.
I think those cases are already tested in unit tests, so validation works, we only need to test that iron form is actually  working here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD15VgM7ZO_XRpvG6vl:-LD15VgM7ZO_XRpvG6vm:b-onlecg) (no related file):*
If I clear a time-picker that has a value (for example the first demo) it's marked as invalid.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by manolo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD15VgM7ZO_XRpvG6vl:-LD1JrLcBneT4fvmHpyN:b-mckun8) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If I clear a time-picker that has a value (for example the first demo) it's marked as invalid.
</blockquote></details>

Yeah, @yuriyvaadin that was the reason of the removed check in the validation, will rollback my last commit and figure out a test for that

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by YuriyVaadin** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD15VgM7ZO_XRpvG6vl:-LD1P4h04jV27LvlxsKN:b-k8982w) (no related file):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Yeah, @yuriyvaadin that was the reason of the removed check in the validation, will rollback my last commit and figure out a test for that
</blockquote></details>

Ok, sorry for the confusion. Haven't taken into account that case.

---

*[test/form-input.html, line 196 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD0jDpt-Kh2Sm4sjpuJ:-LD1PKci9tT0896_xOMy:b4t0ndq) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/0092a70c9c4c9223aaf361a89c51702b2f842224/test/form-input.html#L196)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I'm covering the same cases than in date-picker, plus a couple of specific things.
I think those cases are already tested in unit tests, so validation works, we only need to test that iron form is actually  working here.
</blockquote></details>

Unit tests seems to be checking only attribute/property existence, but not the behaviour on submission of the `iron-form`.
For example, something like this: 
```
it('should not pass the value when disabled', () => {
  timepicker.value = '23:00';
  timepicker.disabled = true;
  expect(ironForm.serializeForm().foo).to.be.equal(undefined);
});
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by YuriyVaadin** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by manolo** [comment]
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/form-input.html, line 196 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD0jDpt-Kh2Sm4sjpuJ:-LD1m6hc3-SyF_2zctPw:bkengpj) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/0092a70c9c4c9223aaf361a89c51702b2f842224/test/form-input.html#L196)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Unit tests seems to be checking only attribute/property existence, but not the behaviour on submission of the `iron-form`.
For example, something like this: 
```
it('should not pass the value when disabled', () => {
  timepicker.value = '23:00';
  timepicker.disabled = true;
  expect(ironForm.serializeForm().foo).to.be.equal(undefined);
});
```
</blockquote></details>

Added your test, thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by manolo** [comment]
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD15VgM7ZO_XRpvG6vl:-LD1mByZEbrECofOpHpH:b-l78zj2) (no related file):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Ok, sorry for the confusion. Haven't taken into account that case.
</blockquote></details>

@tomivirkki it's fixed now. Also removed code to override user's input as was discussed in chat.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD15VgM7ZO_XRpvG6vl:-LD1nCUEB_nV5ygTm02M:b-8fx2u7) (no related file):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

@tomivirkki it's fixed now. Also removed code to override user's input as was discussed in chat.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by tomivirkki** [comment]
*[demo/time-picker-advanced-demos.html, line 9 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD1nHWVAhnRS9bngI2x:-LD1nHWVAhnRS9bngI2y:b-pvscr6) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c7cf9de193a6a91bf41acb509deca40d8600b7a1/demo/time-picker-advanced-demos.html#L9)):*
> ```HTML
> 
>     </style>
>     <h3>Custom Validator</h3>
> ```

This demo throws a console error whenever I select one of the options from the dropdown

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by manolo** [comment]
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/time-picker-advanced-demos.html, line 9 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD1nHWVAhnRS9bngI2x:-LD1slIE-6goHTB7q3TK:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/c7cf9de193a6a91bf41acb509deca40d8600b7a1/demo/time-picker-advanced-demos.html#L9)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This demo throws a console error whenever I select one of the options from the dropdown
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by YuriyVaadin** [comment]
:lgtm:
Please remove trailing spaces from `form-input` test

---

Reviewed 2 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/form-input.html, line 217 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD5_etd41FmDe_w-MW3:-LD5_etd41FmDe_w-MW4:b-62ayx5) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/b5a35e53755bfade0265fa7bbaae5b560243b841/test/form-input.html#L217)):*
> ```HTML
>         timepicker.disabled = true;
>         expect(ironForm.serializeForm().foo).to.be.equal(undefined);
>       });      
> ```

nit: trailing spaces.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-:-LD5_kIkCXYPE-2eiVPx:b-tzslhx)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/form-input.html, line 217 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD5_etd41FmDe_w-MW3:-LD5ktmrEwjGtt_llH4A:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/b5a35e53755bfade0265fa7bbaae5b560243b841/test/form-input.html#L217)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

nit: trailing spaces.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by tomivirkki** [comment]
*[demo/time-picker-advanced-demos.html, line 24 at r5](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD5mnsfCTrbIhvkBlzf:-LD5mnsg25Fl5uoK7KPU:b10oaw5) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/d73911a48b3770b02a1d799b6825422fc4a74540/demo/time-picker-advanced-demos.html#L24)):*
> ```HTML
>               }
>             }
>             customElements.define('vaadin-time-picker-working-hours', TimePickerWorkingHoursElement);
> ```

If you navigate back to basic demos and then back here, the demo script will try to re-define this element and you get an error. Add a check for customElements.get('vaadin-time-picker-working-hours') before defining. This is a common problem in our demos but should be addressed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by manolo** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/time-picker-advanced-demos.html, line 24 at r5](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-LD5mnsfCTrbIhvkBlzf:-LD6D_iF0_9so2KoURjn:b-mmixwv) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/d73911a48b3770b02a1d799b6825422fc4a74540/demo/time-picker-advanced-demos.html#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If you navigate back to basic demos and then back here, the demo script will try to re-define this element and you get an error. Add a check for customElements.get('vaadin-time-picker-working-hours') before defining. This is a common problem in our demos but should be addressed.
</blockquote></details>

I think that might be covered by `vaadin-demo-helpers` in the same way that it rewrites `addDemoReadyListener` with `addEventListener('WebComponentsReady'` otherwise the check seems redundant when reading the demo code in website.

Fixed with the check by the moment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 1 of 4 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-:-LD6Z_LWDD3w5Fig69Al:bnfp4nl)*

**Comment by manolo** [comment]
Will merge when #27 is done, since this branch is against the other.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26#-:-LD7r8kQ1B9_881HHYgA:b673xb5)*

**Pull request merged**
