### PR TITLE
Consider steps in dropdown items list.

### LINKED ISSUE #6: Reflect resolution in the dropdown steps
child of #1

- Minimum 15 mins
- No differing appearance between the items

### PR DESCRIPTION
**Pull request by manolo**
Fixes #6

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[demo/time-picker-basic-demos.html, line 17 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17#-LBzpG8m5fgaqT9mI9hq:-LBzpG8m5fgaqT9mI9hr:b-ffr833) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/bc17bac14128434d10870b16f1a12a7baabce3c9/demo/time-picker-basic-demos.html#L17)):*
> ```HTML
>     </vaadin-demo-snippet>
> 
>     <h3>Number of Items</h3>
> ```

This demo is a bit strange and doesn't represent any real-life use case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17)*

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/vaadin-time-picker.html, line 130 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17#-LC-1uwo3mwHdIiix9hB:-LC-1uwo3mwHdIiix9hC:b-8sc5m8) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/cee97a5e0ca3cf4b0bf14f2a090627cc16a27f7e/src/vaadin-time-picker.html#L130)):*
> ```HTML
>           for (var hour = 0; hour < 24; hour += hourIncr) {
> 
>             var minIncr = hourIncr == 1 ? step / 60 : 60;
> ```

let, const and var mixed in the same function. Only use let and const

---

*[test/dropdown-test.html, line 20 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17#-LC-2V3x-KScxEQHnkEb:-LC-2V3x-KScxEQHnkEc:bvfc9sg) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/cee97a5e0ca3cf4b0bf14f2a090627cc16a27f7e/test/dropdown-test.html#L20)):*
> ```HTML
> 
>   <script>
>     describe('dropdown test', () => {
> ```

If you change function -> arrow function here, please align the other test file also

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 130 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17#-LC-1uwo3mwHdIiix9hB:-LC-rVE27wxhwB1s3O3b:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/cee97a5e0ca3cf4b0bf14f2a090627cc16a27f7e/src/vaadin-time-picker.html#L130)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

let, const and var mixed in the same function. Only use let and const
</blockquote></details>

Done.

---

*[test/dropdown-test.html, line 20 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17#-LC-2V3x-KScxEQHnkEb:-LC-q_6V7Hu0CAbPmreC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/cee97a5e0ca3cf4b0bf14f2a090627cc16a27f7e/test/dropdown-test.html#L20)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If you change function -> arrow function here, please align the other test file also
</blockquote></details>

Done.

---

*[demo/time-picker-basic-demos.html, line 17 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17#-LBzpG8m5fgaqT9mI9hq:-LC-qYsZ1kfXje67s6-Q:bifd99v) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/bc17bac14128434d10870b16f1a12a7baabce3c9/demo/time-picker-basic-demos.html#L17)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This demo is a bit strange and doesn't represent any real-life use case.
</blockquote></details>

Removed. 
We can add it back when we have a meaningful use-case

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17#-:-LCD0ERVEog3Q4FfrcdT:bnfp4nl)*

**Pull request merged**
