### PR TITLE
Keyboard navigation

### LINKED ISSUE #12: Keyboard navigation support
child of #1

Keyboard input

No strict requirements how. This is a good candidate for iteration during development.

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #12

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[demo/time-picker-basic-demos.html, line 19 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCIq-KBuRDEkC32svV:-LDCIq-L6Xt_1rS_7jnP:b31y2kc) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/demo/time-picker-basic-demos.html#L19)):*
> ```HTML
>     <h3>Value Resolution</h3>
>     <p>
>       The <code>step</code> property specified in seconds affects the resolution of the time picker and visibility of dropdown.
> ```

Nit: 'of dropdown' -> 'of the dropdown'

---

*[src/vaadin-time-picker.html, line 284 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCK9fIBgn0eW1m-Sac:-LDCK9fIBgn0eW1m-Sad:b-etj6fg) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/src/vaadin-time-picker.html#L284)):*
> ```HTML
>               return k;
>             }
>           }
> ```

why not use sexy `filter` instead ? 

```
return ['down', 'up'].filter(k => Polymer.IronA11yKeysBehavior.keyboardEventMatchesKeys(e, k))[0] 
```

But I think this extra method can be removed since the `keyboardEventMatchesKeys` has a better name than this private method name, see my comment below 

---

*[src/vaadin-time-picker.html, line 289 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCMPykBQq6ZXSka8Vo:-LDCMPykBQq6ZXSka8Vp:bt5oeom) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/src/vaadin-time-picker.html#L289)):*
> ```HTML
>          /**
>           * Keyboard navigation
>           */
> ```

Method name is clear enough, remove jsdoc since does not add any extra info to the private method

---

*[src/vaadin-time-picker.html, line 299 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCNk2cEslTsYD7x4NJ:-LDCNk2cEslTsYD7x4NK:b-ruom9d) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/src/vaadin-time-picker.html#L299)):*
> ```HTML
>           let parsedValue = this.__validateTime(this.i18n.parseTime(this.__inputElement.value));
> 
>           switch (this.__eventKey(e)) {
> ```

I think you can remove the private method above, and also the switch statement that normally introduces complexity by a `if` block

```
if (Polymer.IronA11yKeysBehavior.keyboardEventMatchesKeys(e, 'down')) {
  this.__onArrowPressWithStep(-stepResolution, parsedValue);
} else if (Polymer.IronA11yKeysBehavior.keyboardEventMatchesKeys(e, 'up')) {
  this.__onArrowPressWithStep(stepResolution, parsedValue);
}

```

---

*[src/vaadin-time-picker.html, line 334 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCP3OvDJXy1AZjgGh_:-LDCP3OvDJXy1AZjgGha:b218m5l) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/src/vaadin-time-picker.html#L334)):*
> ```HTML
>          */
>         __addStep(msec, step) {
>           const fullDay = 24 * 60 * 60 * 1000;
> ```

I think declaring this variable does not add any info, I would move all the block fixing the`msec` with its comment to this line 

```
__addStep(msec, step) {
           // If ...
          if (msec === 0 && step < 0) {
            msec = 24 * ...
          }

  
}
```

---

*[test/dropdown-test.html, line 43 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCPmUT46uN_X4hlkiV:-LDCPmUT46uN_X4hlkiW:bp8ckmi) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/test/dropdown-test.html#L43)):*
> ```HTML
> 
>       it('vaadin-combo-box-light should not have an empty array as filteredItems if step is less than 15 mins', () => {
>         timePicker.step = 60;
> ```

Use a closed value to 15'  someone might change the code to e.g. 10'  and leave this comment outdated ` timePicker.step =  899;

---

*[test/keyboard-navigation.html, line 37 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCQkNX61_BXT7dvXAE:-LDCQkNX61_BXT7dvXAF:btolhon) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/test/keyboard-navigation.html#L37)):*
> ```HTML
> 
>       beforeEach(() => {
>         timePicker = fixture('default');
> ```

nit one line lambda does not need curly brackets

---

*[test/keyboard-navigation.html, line 48 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCTRe4-WNbr8pTZVLn:-LDCTRe4-WNbr8pTZVLo:b-u6z2ev) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/test/keyboard-navigation.html#L48)):*
> ```HTML
>           timePicker.value = '00:00';
>           arrowUp();
>           expect(timePicker.value).to.be.equal('00:00');
> ```

why value does not change here ? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[demo/time-picker-basic-demos.html, line 19 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCIq-KBuRDEkC32svV:-LDCtObv3AEm6LsQiWPW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/demo/time-picker-basic-demos.html#L19)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Nit: 'of dropdown' -> 'of the dropdown'
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 284 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCK9fIBgn0eW1m-Sac:-LDCtRF015JTT0F5n37J:b-u8lfnd) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/src/vaadin-time-picker.html#L284)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why not use sexy `filter` instead ? 

```
return ['down', 'up'].filter(k => Polymer.IronA11yKeysBehavior.keyboardEventMatchesKeys(e, k))[0] 
```

But I think this extra method can be removed since the `keyboardEventMatchesKeys` has a better name than this private method name, see my comment below 

</blockquote></details>

Updated below.

---

*[src/vaadin-time-picker.html, line 289 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCMPykBQq6ZXSka8Vo:-LDCtUeb0ZTt39xypw5Z:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/src/vaadin-time-picker.html#L289)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Method name is clear enough, remove jsdoc since does not add any extra info to the private method
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 299 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCNk2cEslTsYD7x4NJ:-LDCtW325SA0E2FcVhdz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/src/vaadin-time-picker.html#L299)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think you can remove the private method above, and also the switch statement that normally introduces complexity by a `if` block

```
if (Polymer.IronA11yKeysBehavior.keyboardEventMatchesKeys(e, 'down')) {
  this.__onArrowPressWithStep(-stepResolution, parsedValue);
} else if (Polymer.IronA11yKeysBehavior.keyboardEventMatchesKeys(e, 'up')) {
  this.__onArrowPressWithStep(stepResolution, parsedValue);
}

```



</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 334 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCP3OvDJXy1AZjgGh_:-LDCt_Uz14U7TIew8qqu:bwhglds) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/src/vaadin-time-picker.html#L334)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think declaring this variable does not add any info, I would move all the block fixing the`msec` with its comment to this line 

```
__addStep(msec, step) {
           // If ...
          if (msec === 0 && step < 0) {
            msec = 24 * ...
          }

  
}
```
</blockquote></details>

Moved.

---

*[test/dropdown-test.html, line 43 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCPmUT46uN_X4hlkiV:-LDCtsvT2rv9aGMVe9vv:biuv45j) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/test/dropdown-test.html#L43)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Use a closed value to 15'  someone might change the code to e.g. 10'  and leave this comment outdated ` timePicker.step =  899;
</blockquote></details>

Using `720` (stands for `12` mins) and can equally divide hour. `899` is giving not obvious result.
Should I implement the same behaviour as native input does for steps that are not equally dividing time?

---

*[test/keyboard-navigation.html, line 37 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCQkNX61_BXT7dvXAE:-LDCtb6e695cRGFmqgMb:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/test/keyboard-navigation.html#L37)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

nit one line lambda does not need curly brackets
</blockquote></details>

Updated.

---

*[test/keyboard-navigation.html, line 48 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCTRe4-WNbr8pTZVLn:-LDCu7MUC3RsoLo_UaA_:bgrpjy2) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/test/keyboard-navigation.html#L48)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why value does not change here ? 
</blockquote></details>

Value should not be changing on arrows to follow the same behaviour logic as combo-box has: it's not selecting/changing the value on arrows.
Discussed with Jouni.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/dropdown-test.html, line 43 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCPmUT46uN_X4hlkiV:-LDCwit5-F4qHMGcf4cv:b-k2280m) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/test/dropdown-test.html#L43)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Using `720` (stands for `12` mins) and can equally divide hour. `899` is giving not obvious result.
Should I implement the same behaviour as native input does for steps that are not equally dividing time?
</blockquote></details>

In this test updated to `899`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)*

**Comment by manolo** [comment]
Reviewed 2 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 316 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCwlMV-KVWpzMLMXBO:-LDCwlMV-KVWpzMLMXBP:b-uah70w) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/f5ad8e2167779bc44f7446e53f1ca26a8c5e2b57/src/vaadin-time-picker.html#L316)):*
> ```HTML
>          */
>         __addStep(msec, step) {
>           const stepMsec = step * 1000;
> ```

nit: at the same time move this below the block, so as it is closed to the sentence where it's used

---

*[test/dropdown-test.html, line 43 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCPmUT46uN_X4hlkiV:-LDCyjcME0VRq3rTCksx:bhgv1y6) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/test/dropdown-test.html#L43)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

In this test updated to `899`
</blockquote></details>

Yes, please follow native behavior

---

*[test/keyboard-navigation.html, line 48 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCTRe4-WNbr8pTZVLn:-LDCxHMiCbMo41Mh3Og2:b-q8ilnv) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/test/keyboard-navigation.html#L48)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Value should not be changing on arrows to follow the same behaviour logic as combo-box has: it's not selecting/changing the value on arrows.
Discussed with Jouni.
</blockquote></details>

gotcha

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)*

**Comment by YuriyVaadin** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 316 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCwlMV-KVWpzMLMXBO:-LDDB0lWEZF69CA6VD-M:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/f5ad8e2167779bc44f7446e53f1ca26a8c5e2b57/src/vaadin-time-picker.html#L316)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

nit: at the same time move this below the block, so as it is closed to the sentence where it's used
</blockquote></details>

Done.

---

*[test/dropdown-test.html, line 43 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDCPmUT46uN_X4hlkiV:-LDDAxVtAEv65j8EyISA:b-3zzf1m) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/3c506cc4e9e54887da4731be62ce6e7e1a7a5eb5/test/dropdown-test.html#L43)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Yes, please follow native behavior
</blockquote></details>

Added check and test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)*

**Comment by manolo** [comment]
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[src/vaadin-time-picker.html, line 280 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDGDAQB2KW2pVT27-1q:-LDGDAQB2KW2pVT27-1r:bflm6gd) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/5282a1caa8d9a607b54f6ed341c7389993d01f67/src/vaadin-time-picker.html#L280)):*
> ```HTML
>          * Returning true in case day can be equally divided by step value
>          */
>         __validateStep(step) {
> ```

Is necessary this private method that is only used once?  you don't have methods for other cases like this.
Probably a self-explained var is enough `const isValidDayDivisor = 24 * 3600 % step === 0` 

---

*[src/vaadin-time-picker.html, line 287 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDGEJ0s39KkaFEQubfU:-LDGEJ0s39KkaFEQubfV:b-rds1u1) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/5282a1caa8d9a607b54f6ed341c7389993d01f67/src/vaadin-time-picker.html#L287)):*
> ```HTML
>           const stepResolution = this.__validateStep(this.step) && this.step || 60;
> 
>           if (stepResolution >= 15 * 60) {
> ```

In native, when step is invalid e.g. 1500 (25 min) , it always default to 60 but we show one hour selector.
 I think we should do the same  and not open the overlay when step is invalid, but default to 60
Do not change step value, keep 1500 but behave as 60 as native

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)*

**Comment by manolo** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/vaadin-time-picker.html, line 280 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDGDAQB2KW2pVT27-1q:-LDGG-uwB_ahv8BvfjYm:b9i9wal) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/5282a1caa8d9a607b54f6ed341c7389993d01f67/src/vaadin-time-picker.html#L280)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Is necessary this private method that is only used once?  you don't have methods for other cases like this.
Probably a self-explained var is enough `const isValidDayDivisor = 24 * 3600 % step === 0` 
</blockquote></details>

Anyways, if you maintain the method, because based on my comment below, you will need it in `__generateDropdownList` to skip dropdown when step is invalid, it's better to maintain jsdoc for this method, instead rename it so as it's name explain what it does e.g. `__validDayDivisor` 

---

*[src/vaadin-time-picker.html, line 353 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDGG__u6lHX0ugycR33:-LDGG__u6lHX0ugycR34:b3lyevz) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/5282a1caa8d9a607b54f6ed341c7389993d01f67/src/vaadin-time-picker.html#L353)):*
> ```HTML
> 
>         __generateDropdownList() {
>           if (this.step < 15 * 60) {
> ```

To behave as native this should be `if (this.step < 15 * 60 || !_validate(step))` 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)*

**Comment by YuriyVaadin** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 280 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDGDAQB2KW2pVT27-1q:-LDGmfPE9Vbw7bxNjBuk:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/5282a1caa8d9a607b54f6ed341c7389993d01f67/src/vaadin-time-picker.html#L280)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Anyways, if you maintain the method, because based on my comment below, you will need it in `__generateDropdownList` to skip dropdown when step is invalid, it's better to maintain jsdoc for this method, instead rename it so as it's name explain what it does e.g. `__validDayDivisor` 
</blockquote></details>

Updated.

---

*[src/vaadin-time-picker.html, line 287 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDGEJ0s39KkaFEQubfU:-LDGmg_B-EWVfLSZ3QHQ:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/5282a1caa8d9a607b54f6ed341c7389993d01f67/src/vaadin-time-picker.html#L287)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

In native, when step is invalid e.g. 1500 (25 min) , it always default to 60 but we show one hour selector.
 I think we should do the same  and not open the overlay when step is invalid, but default to 60
Do not change step value, keep 1500 but behave as 60 as native

</blockquote></details>

Updated.

---

*[src/vaadin-time-picker.html, line 353 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDGG__u6lHX0ugycR33:-LDGmh7e5OSztPEWze1d:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/5282a1caa8d9a607b54f6ed341c7389993d01f67/src/vaadin-time-picker.html#L353)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

To behave as native this should be `if (this.step < 15 * 60 || !_validate(step))` 
</blockquote></details>

Updated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)*

**Comment by manolo** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/dropdown-test.html, line 47 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDGoyUm-jH9rmEYKIF3:-LDGoyUm-jH9rmEYKIF4:b1huf5k) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/0cef74bc91346c105e5b987c098d89570a7a6c36/test/dropdown-test.html#L47)):*
> ```HTML
>       });
> 
>       it('vaadin-combo-box-light should not have an empty array as filteredItems if step is bigger than 15 mins', () => {
> ```

I think description is incorrect? I expect :100: 

`vaadin-combo-box-light should have an empty array if step is not a divisor of day` 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)*

**Comment by YuriyVaadin** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/dropdown-test.html, line 47 at r4](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-LDGoyUm-jH9rmEYKIF3:-LDGv542EUw6gDTUYGto:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/0cef74bc91346c105e5b987c098d89570a7a6c36/test/dropdown-test.html#L47)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think description is incorrect? I expect :100: 

`vaadin-combo-box-light should have an empty array if step is not a divisor of day` 


</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)*

**Comment by manolo** [comment]
good job!  :lgtm:  

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29#-:-LDGyEqgCkfoiaKoBWnJ:b-dbsa8i)*

**Pull request merged**
