### PR TITLE
Step property

### LINKED ISSUE #4: Add step property
child of #1

- Number, seconds
- defines the resolution of the component
- Accepts only values that can divide a unit evenly
- Doesn’t cause limitations to text input
- Demo & tests

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #4

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[demo/time-picker-basic-demos.html, line 19 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtGXS11IuhjQ3vJlYZ:-LBtGXS11IuhjQ3vJlY_:b-uqi5jt) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/8e554333e3ea4abc30b87e2f0e5a47d25f3e9207/demo/time-picker-basic-demos.html#L19)):*
> ```HTML
>     <h3>Step Value</h3>
>     <p>
>       Step property/attribute specified in seconds is affecting resolution of the time picker.
> ```

Change with  `The <code>step<code> property specified  in seconds affects .... ` (no need to mention attribute since readers are familiar with polymer' 

---

*[src/vaadin-time-picker.html, line 144 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtFySk7_oUhQRSy8tu:-LBtFySk7_oUhQRSy8tv:b6i6in9) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/8e554333e3ea4abc30b87e2f0e5a47d25f3e9207/src/vaadin-time-picker.html#L144)):*
> ```HTML
>             default:
>               return;
>           }
> ```

Isn't this the same than `return parts.slice(1, this._stepSegment + 1)` ? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 121 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtSUSG5vxosAgYrjbz:-LBtSUSHBrSQk8dZgr7f:bb7j688) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/8e554333e3ea4abc30b87e2f0e5a47d25f3e9207/src/vaadin-time-picker.html#L121)):*
> ```HTML
>             // Accept milliseconds
>             return 4;
>           } else {
> ```

unnecessary else

---

*[src/vaadin-time-picker.html, line 163 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtSXzlDNmFJ9WL2EsW:-LBtSXzlDNmFJ9WL2EsX:b-f8jd43) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/8e554333e3ea4abc30b87e2f0e5a47d25f3e9207/src/vaadin-time-picker.html#L163)):*
> ```HTML
>             case 4:
>               return `${hours}:${minutes ? minutes : '00'}:${seconds ? seconds : '00'}.${milliseconds ? milliseconds : '000'}`;
>             default:
> ```

unnecessary  block default

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[demo/time-picker-basic-demos.html, line 19 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtGXS11IuhjQ3vJlYZ:-LBtU5zt3JlFL-DFhaNE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/8e554333e3ea4abc30b87e2f0e5a47d25f3e9207/demo/time-picker-basic-demos.html#L19)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Change with  `The <code>step<code> property specified  in seconds affects .... ` (no need to mention attribute since readers are familiar with polymer' 
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 121 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtSUSG5vxosAgYrjbz:-LBtUwSL3ZwY4z4I7ZfW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/8e554333e3ea4abc30b87e2f0e5a47d25f3e9207/src/vaadin-time-picker.html#L121)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

unnecessary else
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 144 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtFySk7_oUhQRSy8tu:-LBtUTfUCwMAyU1yOJj7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/8e554333e3ea4abc30b87e2f0e5a47d25f3e9207/src/vaadin-time-picker.html#L144)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Isn't this the same than `return parts.slice(1, this._stepSegment + 1)` ? 
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 149 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtSif07CbmrVXAeHC9:-LBtUU22DVlktNpor537:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/8e554333e3ea4abc30b87e2f0e5a47d25f3e9207/src/vaadin-time-picker.html#L149)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why returning empty string here, since below default returns undefined
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 163 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtSXzlDNmFJ9WL2EsW:-LBtUV9DECC1yveIM2UO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/8e554333e3ea4abc30b87e2f0e5a47d25f3e9207/src/vaadin-time-picker.html#L163)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

unnecessary  block default
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-:-LBtbbwJ-_Pt446Ts18b:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[src/vaadin-time-picker.html, line 75 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtm9OuBJq1wctardGB:-LBtm9Ov-68vGt0LmIfc:b3vs85u) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/eaf0221a1bedec7126b65ac88423f9367198d061/src/vaadin-time-picker.html#L75)):*
> ```HTML
>               type: Number,
>               observer: '_stepChanged',
>               reflectToAttribute: true,
> ```

Hmm..I don't see a need to reflect this

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14)*

**Comment by YuriyVaadin** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-time-picker.html, line 75 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtm9OuBJq1wctardGB:-LBu52Fu1WUxXVBqBvHI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/eaf0221a1bedec7126b65ac88423f9367198d061/src/vaadin-time-picker.html#L75)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Hmm..I don't see a need to reflect this
</blockquote></details>

Done.

---

*[src/vaadin-time-picker.html, line 76 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBtulwS0zZfEFBrlHkr:-LBu4ZNk0H4gUNNCIuTE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/eaf0221a1bedec7126b65ac88423f9367198d061/src/vaadin-time-picker.html#L76)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Let's not define a default value for this. The native input type=time also has it empty by default which effectively behaves the same as 60 (seconds)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14)*

**Comment by manolo** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/time-picker-basic-demos.html, line 17 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBu660Q6VTfaFNTcxNU:-LBu7LOy8Mo8EkK0lRY8:bqkyu4l) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/b55374c2ce7ec85457efb376314e07ea98db22d1/demo/time-picker-basic-demos.html#L17)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"Step Value" doesn't sound familiar for someone who doesn't know the api beforehand. Should it be titled something like "Value Resolution" or "Value Granularity"?
</blockquote></details>

Might be "Value Increments" ? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r1, 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-:-LBu7u6OCW5dKaN4UCHI:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/time-picker-basic-demos.html, line 17 at r3](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-LBu660Q6VTfaFNTcxNU:-LBu7rLdC6bxY_HAnTcZ:b36ml4i) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/b55374c2ce7ec85457efb376314e07ea98db22d1/demo/time-picker-basic-demos.html#L17)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Might be "Value Increments" ? 
</blockquote></details>

Changed to `Value Resolution`. We can decide on the naming later on as it anyway will be changed with the updates to `step` functionality

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-:-LBu89nKDJqFp40WX9B0:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r1, 1 of 2 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14#-:-LBu7N_w5TU_ho1zC4dt:bnfp4nl)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14)*

**Pull request merged**
