### PR TITLE
[WIP] Install polymer-cli locally, set code coverage threshold to 98

### PR DESCRIPTION
**Pull request by limonte**
Trying to get the build green...

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/57)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @limonte)

---

*[.travis.yml, line 15 at r1](https://reviewable.io/reviews/vaadin/vaadin-time-picker/57#-LExcFtj2NnIB7DM1Bz9:-LExcFtj2NnIB7DM1BzA:bvbj4il) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/a027a2a4224041126e44c0265a78798aa28c9f3a/.travis.yml#L15)):*
> ```YAML
> 
> before_script:
>   - npm install -g bower polymer-cli@next
> ```

what is the main reason of this ? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/57)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @limonte)

---

*[.travis.yml, line 15 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/57#-LF1lGm48MSjmgInp321:-LF1lGm48MSjmgInp322:bfumb4b) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/9815d634a6ee50b5aef51fe1f4a02ba1b1bbf42a/.travis.yml#L15)):*
> ```YAML
> 
> before_script:
>   - npm install bower polymer-cli@next
> ```

you need to ad `--no-save` in all npm calls so as P3 modulizer does not fail

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/57)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @limonte)

---

*[.travis.yml, line 15 at r2](https://reviewable.io/reviews/vaadin/vaadin-time-picker/57#-LF1lGm48MSjmgInp321:-LF1lTHC-W_pk27vHhb9:b9rwwzo) ([raw file](https://github.com/vaadin/vaadin-time-picker/blob/9815d634a6ee50b5aef51fe1f4a02ba1b1bbf42a/.travis.yml#L15)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

you need to ad `--no-save` in all npm calls so as P3 modulizer does not fail
</blockquote></details>

I think for this component you might take the `.travis.yml` from a `p3-preview` of any element, for instance vaadin-item

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-time-picker/57)*

**Comment by YuriyVaadin** [comment]
Closed as changes were applied on master and https://github.com/vaadin/vaadin-time-picker/pull/62.

**Pull request closed without merging**
